server:
  port: 8082
  servlet :
    context-path: /foodCatalogue
management:
  endpoint:
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    health:
      show-details: always
spring:
  jackson:
     default-property-inclusion: non_null
logging:
  level:
    org:
      springframework:
        web:
          servlet:
            mvc:
              method:
                annotation:
                  RequestResponseBodyMethodProcessor: DEBUG